### ISSUE TITLE
A flag during bean-loading to fail silently for syntax errors

### ISSUE THREAD

**Issue by atuttle** [framework-one/di1#66]
Use-case:

Should a syntax error in a service accidentally slip into production, in a FW/1 + DI/1 app, the whole app goes down because of the error during DI/1 startup. The more graceful solution would be for just the portion of the application that needs this service to fail. In order to do so, DI/1 needs to skip objects it's loading that contain syntax errors which would otherwise cause an exception to be thrown during startup.

Obviously you want to catch these types of errors before they get into production, so you **don't** want this setting on in DEV + QA environments, but I think it would be beneficial to have it as an option in production.

**Comment by seancorfield** [comment]
If you suppress the exception on object creation, I suspect you'd run into an exception immediately after in the call to `init()` or subsequently during autowiring so I don't think this will actually get you very far.

You can test that for yourself by writing a wrapper that extends `framework.ioc` and overrides the `construct()` method to trap/ignore any exceptions (and remember to tell FW/1 to use your wrapper instead, via `diComponent`).

Let me know how that works.

**Comment by atuttle** [comment]
I'm trying to test this, but I don't see any reference to `diComponent` [in the FW/1 source](https://github.com/framework-one/fw1/blob/master/org/corfield/framework.cfc) or documentation -- maybe this is something you haven't pushed yet?

At any rate, I might be able to get by without it. My FW/1 app uses subsystems and I use the `setupSubsystem` override to build subsystem-specific bean factories for each. I imagine it also covers the default subsystem, but I'll test in a non-default just to be sure.

Just wanted to let you know that I've no idea what `diComponent` is referencing, in case you meant to share it. :)

**Comment by atuttle** [comment]
Initial tests don't look good, though. I named my component `iocplus.cfc`, and it contained:

```js
component extends="ioc"{

	function construct( string dottedPath ){
		try {
			return super.construct( dottedPath );
		}catch (any e){
			return {};
		}
	}

}
```

In my Application.cfc, I have these overrides:

```js
function setupApplication(){
	var bf = new framework.iocplus('/com/public');
	setBeanFactory(bf);
	//tell the config service which environment it's running in
	bf.getBean('configService').setEnvironment( getEnvironment() );
}

function setupSubsystem( subsystem ){
	if (subsystem == ']['){ return; } //WAT
	var bf = new framework.iocplus( '/modules/' & arguments.subsystem );
	bf.setParent( getDefaultBeanFactory() );
	setSubsystemBeanFactory( arguments.subsystem, bf );
}
```

And I'm still getting the error message for the syntax error.

Maybe I'm misunderstanding how FW/1 initializes. I'm fine giving up on this ER, but it seems like a good opportunity to learn more about my tools. I was under the impression that FW/1 only loaded the components used for the current request, and cached them at that point; but that would appear not to be the case right now. Maybe it's because I'm using DI/1 and doing so necessitates instantiating the whole object graph on startup?

**Comment by seancorfield** [comment]
You'll need to configure FW/1 to not use DI/1 automatically (since you're not following a standard convention for the location of your subsystem beans). Add `diEngine = "none"` to your `framework` config structure.

**Comment by atuttle** [comment]
Even with the following settings the error still displays at startup :(

```js
variables.framework.diEngine = "none";
variables.framework.diComponent = "framework.iocplus";
```

**Comment by seancorfield** [comment]
Please create the smallest possible test case and email it to me in a ZIP.

**Comment by atuttle** [comment]
Will do!

For what it's worth, while it may not be possible with FW/1, here's a similar implementation that I wrote into Taffy (which partly inspired this request). When a resource cfc has a compile-time error, it's displayed here and all other resources are still fully usable:

![image](https://cloud.githubusercontent.com/assets/46990/6116998/32005e04-b07f-11e4-8cab-2fe3a833a5e2.png)

**Comment by seancorfield** [comment]
This is due to the call to `getComponentMetadata()` which fails if a CFC has syntax errors. I'm going to move that to an extension point, similar to `construct()` and leave it up to developers if they want to override the behavior.

**Comment by atuttle** [comment]
So taking this back to the original use-case, let's say I update my `iocplus.cfc` as below. I've made some interface assumptions based on the way metadata is currently loaded, but it should at least paint the picture... Is this what you had in mind?

```js
component extends="ioc"{

	function init( string folders, struct config = {}, boolean silentFail = false ){
		variables.silentFail = arguments.silentFail;
		return super.init( folders, config );
	}

	function construct( string dottedPath ){
		if (variables.silentFail){
			try {
				return super.construct( dottedPath );
			}catch( any e ){
				return {};
			}
		}else{
			return super.construct( dottedPath );
		}
	}

	function loadMetaData( string cfc ){
		if (variables.silentFail){
			try {
				return super.loadMetaData( cfc );
			}catch( any e ){
				//might need some dummy attributes, like functions:[] 
				//to get everything working as needed
				return {};
			}
		}else{
			return super.loadMetaData( cfc );
		}
	}

}
```

**Comment by seancorfield** [comment]
That's about it. Better to make `silentFail` a member in `config`, IMO, so you can leverage the automatic FW/1 / DI/1 relationship (with `diComponent = 'framework.iocplus'`) but that's the sort of extend-and-override I was thinking of. And it'll likely be `metadata()` as the method name.

**Comment by seancorfield** [comment]
Fixed via https://github.com/framework-one/fw1/commit/5a63360712f1a447c102adf3362a5f78de7a56bf by adding `metadata()` as an extension point. I'll update the documentation and then close this ticket.

**Comment by seancorfield** [comment]
Using DI/1 documentation updated.

**Comment by atuttle** [comment]
Works like a charm!
